### ISSUE TITLE
Lua profiler for nvim

### ISSUE THREAD

**Issue by clason** [tjdevries/lua.nvim#1]
One useful addition to a nvim-lua standard library would be a profiler (since the vim `prof func *` can't trace into lua). I've played a bit with the `debug.sethook` based approach, either using https://stackoverflow.com/questions/15725744/easy-lua-profiling or https://github.com/charlesmallah/lua-profiler.

Both _kinda_ work, but it'd be nice to have something more nvim-aware (and prettier) :)

There's also https://blast.hk/moonloader/luajit/ext_profiler.html, but I couldn't get this to work properly.

**Comment by matu3ba** [comment]
Can you update the issue regarding what is missing from your merged PR to plenary? :)
